version: "3"
services:
  customer:
    build: .
    ports:
      - 8080:8080
    links:
      - db
    environment:
      - PGPASSWORD=intuit_awesomeness
      - PGDATABASE=intuit_awesomeness
      - PGHOST=db:5432
      - PGUSER=postgres
    depends_on:
      - "db"

  #frontend:
   # build: frontend
    #ports:
     # - 9000:80

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=intuit_awesomeness
      - POSTGRES_DB=intuit_awesomeness
